### ISSUE TITLE
Linux arm64 ffmpeg download support?

### ISSUE THREAD

**Issue by henrikp** [ffbinaries/ffbinaries-node#34]
Hi, since you are already using the prebuilt binaries from [https://www.johnvansickle.com/ffmpeg/](url) could you include arm64 binaries as well with the automatic downloader? Currently I had to manually download them and they work fine, atleast with mStream.

**Comment by vot** [comment]
Hi @henrikp, I just added the FFmpeg 4.4.1 binaries which include arm-64 architecture.

Not sure why you had issues in the past though since arm-64 builds have been included for a while, let me know if this is now resolved :)

**Comment by henrikp** [comment]
Latest docker image (v5.9.4-ls69), getting ffmpeg to download seems to be a problem (for me only?). 

When I only mount `/config` and `/music` ffmpeg doesn't get downloaded into the container.


```
v5.9.4


Check out our Discord server:

https://discord.gg/AM896Rr


2022-01-09T12:59:38.421Z info: Checking ffmpeg...

2022-01-09T12:59:38.467Z error: Failed to download FFmpeg

Error: EACCES: permission denied, mkdir '/ffmpeg'

    at Object.mkdirSync (fs.js:1013:3)

    at ensureDirSync (/opt/mstream/node_modules/ffbinaries/ffbinaries-lib.js:26:9)

    at Object.downloadBinaries (/opt/mstream/node_modules/ffbinaries/ffbinaries-lib.js:337:3)

    at /opt/mstream/src/api/transcode.js:50:16

    at new Promise (<anonymous>)

    at init (/opt/mstream/src/api/transcode.js:45:10)

    at Object.exports.setup (/opt/mstream/src/api/transcode.js:111:5)

    at Object.exports.serveIt (/opt/mstream/src/server.js:143:12)

2022-01-09T12:59:38.476Z info: Access mStream locally: http://localhost:3000

2022-01-09T12:59:53.536Z info: File scan started on /music
```

I went into the container and there wasn't any `/ffmpeg` indeed.  Was running with the default container user and group. 

Though when I mounted `/ffmpeg` to a local path, binaries did get downloaded and everything worked as it should, both buffer and stream mode.

**Comment by vot** [comment]
Hmm this looks like an issue within the docker container.
I'm not sure what the typical way of running mStream container would be but I can see other people have run into similar problems (https://github.com/linuxserver/docker-mstream/issues/4 - I'm assuming this is the image you're using?).

With that in mind it feels like something that could probably be incorporated into that container in a cleaner way. I'm thinking perhaps downloading the binaries during the build of the Docker image might be the way to go - that way the binaries would be bundled with the build and you wouldn't have to deal with the permissions at all.

One thing worth pointing out is that the directory for the binaries would be /opt/mstream/bin/ffmpeg (which should have a readme file in it already).

**Comment by henrikp** [comment]
> Hmm this looks like an issue within the docker container. I'm not sure what the typical way of running mStream container would be but I can see other people have run into similar problems ([linuxserver/docker-mstream#4](https://github.com/linuxserver/docker-mstream/issues/4) - I'm assuming this is the image you're using?).

Yes.
> 
> With that in mind it feels like something that could probably be incorporated into that container in a cleaner way. I'm thinking perhaps downloading the binaries during the build of the Docker image might be the way to go - that way the binaries would be bundled with the build and you wouldn't have to deal with the permissions at all.

Including them during the build would be the most direct course, as I see it, you can't use that docker image anywhere else anyway. 
> 
> One thing worth pointing out is that the directory for the binaries would be /opt/mstream/bin/ffmpeg (which should have a readme file in it already).

During the initial troubleshooting I changed the paths for some reason and forgot to change them back in the configuration file.

**Comment by vot** [comment]
Hi @henrikp, I just tried running docker-mstream image locally and it all appeared to function just fine on an x64 architecture (including the download of the ffmpeg binary).

 What's the platform you're running into this issue with, is it a Raspberry Pi?

**Comment by henrikp** [comment]
> Hi @henrikp, I just tried running docker-mstream image locally and it all appeared to function just fine on an x64 architecture (including the download of the ffmpeg binary).
> 
> What's the platform you're running into this issue with, is it a Raspberry Pi?

Yes. Raspberry Pi 4 with aarch64. 
```
  mstream:
    container_name: mstream
    hostname: mstream
    image: lscr.io/linuxserver/mstream
    restart: unless-stopped
    environment:
      - PUID=${G_PUID}
      - PGID=${G_PGID}
      - TZ=${G_TZ}
    volumes:
      - /local/path/config:/config
      - /local/path/ffmpeg:/opt/mstream/bin/ffmpeg 
      - /local/path/music:/music
```
