### ISSUE TITLE
Download zip fow windows contains __MACOSX folder

### ISSUE THREAD

**Issue by flq** [ffbinaries/ffbinaries-node#36]
Not sure if this is the right place to report this, but anyway, here goes:

Since the 8th of January there is a new version downloadable at https://ffbinaries.com/

Now, when our downloader lib (running on Windows) gets the latest version, the zip file also contains a folder which apparently seems to be for OSX systems:

![image](https://user-images.githubusercontent.com/123748/148788445-6463b14e-cf07-4c07-8275-1a3f53a3c9c9.png)

Apart from it not making any sense, it also breaks the unzipper of the downloader lib, because it appears that it is running without creating subfolders when necessary.

As a workaround we now create the sub-folder and the file correctly unzips. However, to avoid future support issues it may make sense to package the windows version on its own.

**Comment by vot** [comment]
Hi @flq, thanks for raising an issue.

This is simply an artifact of zipping the binaries from a MacOS machine and serves no purpose, it's actually been included in all previous versions as well (I repackage the binaries manually since I haven't been able to achieve the same compression ratio using command line - FWIW I haven't tried all that hard :D ).

Has this only started being an issue with v4.4.1?

**Comment by flq** [comment]
Hi there, thanks for coming up. Yes strangely enough it only became a reason on with the latest version - there is a .NET package to use this library, and its downloader has an issue with creating the folder to unpack its content. Now that you say this folder has been there all along I'm not sure what the difference is. If you can't do much about it, I suggest to close - from the version history it doesn't look like a version upgrade happens many times.

**Comment by vot** [comment]
Hi @flq, yeah I was wondering why people I got two issues raised about this - it makes more sense now with that extra context, thanks :D

I'm repacking all the binaries in this release, they should be ready in the next 20 minutes or so :)
Once verified I'll also add a note about repack on ffbinaries.com to inform other people who may be facing this.

**Comment by flq** [comment]
Didn'see the edit 🤦🏻‍♂️ - yes, all good
