### ISSUE TITLE
Include binaries for arm64 architecture - linux

### ISSUE THREAD

**Issue by Hi7cl4w** [ffbinaries/ffbinaries-node#39]
Currently, arm64 architecture Linux is not supported

**Comment by aaronjamt** [comment]
Fixed by #47, the next release should support ARM64

**Comment by vot** [comment]
@Hi7cl4w @aaronjamt

Fix for arm64 architecture detection has now been published as v1.1.6.

**Comment by aaronjamt** [comment]
> @Hi7cl4w @aaronjamt
> 
> Fix for arm64 architecture detection has now been published as v1.1.6.

Great, thanks!
