### ISSUE TITLE
Would it be possible to add support for version 5?

### ISSUE THREAD

**Issue by justinStoner** [ffbinaries/ffbinaries-node#42]
Would be open to submitting a PR for it

**Comment by vot** [comment]
Hi @justinStoner,

Support for versions 5.1 and 6.1 has just been added.

You can download ffmpeg 5.1 like this: `ffbinaries ffmpeg -v=5.1`

Currently the `latest` tag is still pointing at 4.4.1 to prevent any issues, I will bump that to the newest version in about a month's time.
